name: Trigger Weekly Release

on:
  schedule:
    - cron: '0 0 * * 3'  # 每周三 00:00 UTC
  workflow_dispatch:

jobs:
  trigger-release:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deno Deploy webhook
        run: |
          curl -X POST https://auto-release.deno.dev \
          -H "Content-Type: application/json" \
          -H "x-hub-signature-256: sha256=$(echo -n "${{ secrets.WEBHOOK_PAYLOAD }}" | openssl dgst -sha256 -hmac "${{ secrets.WEBHOOK_SECRET }}" | cut -d' ' -f2)" \
          -d '{"schedule":"weekly"}'
        env:
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}